### ISSUE TITLE
Switch to Wezterm

### ISSUE THREAD

**Issue by redactedontop** [arithefirst/dotfiles#4]
Hi! As ghostty is in private beta, and as I believe wezterm is as (if not more) performant, I'd politely ask for a switch.

Also, what is your motive for using ghostty?

**Comment by arithefirst** [comment]
> Hi! As Ghostty is in private beta, and as I believe Wezterm is as (if not more) performant, I'd politely ask for a switch.

Ghostty is faster than wezterm, and even otherwise, I'm not going to write an entire configuration for a terminal I will never use because some guy on the internet was too lazy to make his own, nor will I be switching terminals, if that's what you tried to imply. This repo's primary function is not for other people to clone my configurations, it's for **my** configuration for **me**. Letting other people copy my dotfiles is not by any means the primary focus of this repository. If I need to go install my Ghostty dotfiles, and I have Wezterm dotfiles here, how does that help me? If you really want Wezterm to look like my Ghostty config, then go write one your self.

> Also, what is your motive for using Ghostty?

It shouldn't matter at all, as you have no place to question my motives, but I like it's speed and config style as well as support for shaders.

**Comment by redactedontop** [comment]
1st (speed): https://www.youtube.com/watch?v=VMdSJ8d5Aos
2nd (motives): I was just curious, but mkay...
3rd (dotfiles copying): I understand mate, cheers.

**Comment by arithefirst** [comment]
> 1st (speed): https://www.youtube.com/watch?v=VMdSJ8d5Aos&t=18s

I did my own testing yesterday, and found Ghostty significantly outperformed Wezterm. Different performances occur on different GPUs

**Comment by redactedontop** [comment]
Did you set animation_fps to 255 (I'm begging the dev to set the limit as an option soon, dw) and the render mode to webgpu? Animation FPS isn't handled by the wayland compositor yet.

**Comment by arithefirst** [comment]
No, and frankly I do not care to. The speed difference between the two would still be relatively un-noticable in day to day use, and wezterm is ugly anyways. I'm also locking this thread because it should have been done days ago/never started in the first place.
